# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0005_usuario_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('nombre', models.TextField()),
                ('latitud', models.DecimalField(max_digits=20, decimal_places=18)),
                ('longitud', models.DecimalField(max_digits=20, decimal_places=18)),
            ],
        ),
        migrations.RemoveField(
            model_name='conversacion',
            name='busqueda',
        ),
        migrations.RemoveField(
            model_name='conversacion',
            name='respuesta',
        ),
        migrations.RemoveField(
            model_name='cuestionario',
            name='preguntas',
        ),
        migrations.RemoveField(
            model_name='cuestionariopregunta',
            name='cuestionario',
        ),
        migrations.RemoveField(
            model_name='cuestionariopregunta',
            name='dependencia_respuestas',
        ),
        migrations.RemoveField(
            model_name='cuestionariopregunta',
            name='pregunta',
        ),
        migrations.RemoveField(
            model_name='cuestionariorol',
            name='cuestionario',
        ),
        migrations.RemoveField(
            model_name='cuestionariorol',
            name='rol',
        ),
        migrations.RemoveField(
            model_name='mensaje',
            name='conversacion',
        ),
        migrations.RemoveField(
            model_name='mensaje',
            name='destinatario',
        ),
        migrations.RemoveField(
            model_name='mensaje',
            name='usuario_busqueda',
        ),
        migrations.RemoveField(
            model_name='mensaje',
            name='usuario_respuesta',
        ),
        migrations.RemoveField(
            model_name='opcionesderespuesta',
            name='pregunta',
        ),
        migrations.RemoveField(
            model_name='preguntassimilitud',
            name='funcion',
        ),
        migrations.RemoveField(
            model_name='preguntassimilitud',
            name='pregunta_A',
        ),
        migrations.RemoveField(
            model_name='preguntassimilitud',
            name='pregunta_B',
        ),
        migrations.RemoveField(
            model_name='problemasolucion',
            name='categorias',
        ),
        migrations.RemoveField(
            model_name='problemasolucion',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='problemasolucion',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='problemasolucionopcionrespuesta',
            name='opcion_respuesta',
        ),
        migrations.RemoveField(
            model_name='problemasolucionopcionrespuesta',
            name='problema_solucion',
        ),
        migrations.RemoveField(
            model_name='respuestaproblemasolucion',
            name='busqueda',
        ),
        migrations.RemoveField(
            model_name='respuestaproblemasolucion',
            name='respuesta',
        ),
        migrations.RemoveField(
            model_name='rol',
            name='cuestionarios',
        ),
        migrations.RemoveField(
            model_name='usuarioredes',
            name='red_social',
        ),
        migrations.RemoveField(
            model_name='usuarioredes',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Variable',
        ),
        migrations.DeleteModel(
            name='Conversacion',
        ),
        migrations.DeleteModel(
            name='Cuestionario',
        ),
        migrations.DeleteModel(
            name='CuestionarioPregunta',
        ),
        migrations.DeleteModel(
            name='CuestionarioRol',
        ),
        migrations.DeleteModel(
            name='Mensaje',
        ),
        migrations.DeleteModel(
            name='OpcionesDeRespuesta',
        ),
        migrations.DeleteModel(
            name='Pregunta',
        ),
        migrations.DeleteModel(
            name='PreguntasSimilitud',
        ),
        migrations.DeleteModel(
            name='ProblemaSolucion',
        ),
        migrations.DeleteModel(
            name='ProblemaSolucionOpcionRespuesta',
        ),
        migrations.DeleteModel(
            name='RedSocial',
        ),
        migrations.DeleteModel(
            name='RespuestaProblemaSolucion',
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
        migrations.DeleteModel(
            name='Similitud',
        ),
        migrations.DeleteModel(
            name='UsuarioRedes',
        ),
    ]
